"use strict";

/**
 * HanziFlow — Vocabulary list
 * Schema: { fr: string, pinyin: string, hanzi: string }
 * Notes:
 * - Keep this file as pure data.
 * - Consistent casing and punctuation.
 */

window.VOCAB = [
  { fr: "je / moi", pinyin: "wǒ", hanzi: "我" },
  { fr: "tu / toi", pinyin: "nǐ", hanzi: "你" },
  { fr: "il / elle", pinyin: "tā", hanzi: "他/她/它" },
  { fr: "nous", pinyin: "wǒmen", hanzi: "我们" },
  { fr: "vous", pinyin: "nǐmen", hanzi: "你们" },
  { fr: "ils / elles", pinyin: "tāmen", hanzi: "他们/她们/它们" },
  { fr: "ceci", pinyin: "zhè", hanzi: "这" },
  { fr: "cela", pinyin: "nà", hanzi: "那" },
  { fr: "ces", pinyin: "zhèxiē", hanzi: "这些" },
  { fr: "ceux-là / Celles-là / Ces... (éloignés)", pinyin: "nàxiē", hanzi: "那些" },
  { fr: "ici", pinyin: "zhèlǐ", hanzi: "这里" },
  { fr: "là-bas", pinyin: "nàlǐ", hanzi: "那里" },
  { fr: "Chine", pinyin: "zhōngguó", hanzi: "中国" },
  { fr: "langue chinoise", pinyin: "zhōngwén", hanzi: "中文" },
  { fr: "personne", pinyin: "rén", hanzi: "人" },
  { fr: "prénom", pinyin: "míngzì", hanzi: "名字" },
  { fr: "maman", pinyin: "māma", hanzi: "妈妈" },
  { fr: "papa", pinyin: "bàba", hanzi: "爸爸" },
  { fr: "grand frère", pinyin: "gēge", hanzi: "哥哥" },
  { fr: "petit frère", pinyin: "dìdi", hanzi: "弟弟" },
  { fr: "grande sœur", pinyin: "jiějie", hanzi: "姐姐" },
  { fr: "petite sœur", pinyin: "mèimei", hanzi: "妹妹" },
  { fr: "grand-père", pinyin: "yéye", hanzi: "爷爷" },
  { fr: "grand-mère", pinyin: "nǎinai", hanzi: "奶奶" },
  { fr: "ami", pinyin: "péngyou", hanzi: "朋友" },
  { fr: "enfant", pinyin: "háizi", hanzi: "孩子" },
  { fr: "endroit", pinyin: "dìfāng", hanzi: "地方" },
  { fr: "maison / famille", pinyin: "jiā", hanzi: "家" },
  { fr: "magasin", pinyin: "shāngdiàn", hanzi: "商店" },
  { fr: "argent", pinyin: "qián", hanzi: "钱" },
  { fr: "travail", pinyin: "gōngzuò", hanzi: "工作" },
  { fr: "appartement", pinyin: "gōngyù", hanzi: "公寓" },
  { fr: "pièce", pinyin: "fángjiān", hanzi: "房间" },
  { fr: "voiture", pinyin: "chē", hanzi: "车" },
  { fr: "route", pinyin: "lù", hanzi: "路" },
  { fr: "eau", pinyin: "shuǐ", hanzi: "水" },
  { fr: "thé", pinyin: "chá", hanzi: "茶" },
  { fr: "café", pinyin: "kāfēi", hanzi: "咖啡" },
  { fr: "plat", pinyin: "fàn", hanzi: "饭" },
  { fr: "électricité", pinyin: "diàn", hanzi: "电" },
  { fr: "téléphone portable", pinyin: "shǒujī", hanzi: "手机" },
  { fr: "livre", pinyin: "shū", hanzi: "书" },
  { fr: "aujourd'hui", pinyin: "jīntiān", hanzi: "今天" },
  { fr: "demain", pinyin: "míngtiān", hanzi: "明天" },
  { fr: "hier", pinyin: "zuótiān", hanzi: "昨天" },
  { fr: "après-demain", pinyin: "hòutiān", hanzi: "后天" },
  { fr: "temps", pinyin: "shíjiān", hanzi: "时间" },
  { fr: "minute", pinyin: "fēnzhōng", hanzi: "分钟" },
  { fr: "année", pinyin: "nián", hanzi: "年" },
  { fr: "mois", pinyin: "yuè", hanzi: "月" },
  { fr: "jour", pinyin: "rì", hanzi: "日" },
  { fr: "semaine", pinyin: "xīngqī", hanzi: "星期" },
  { fr: "intérieur", pinyin: "lǐmiàn", hanzi: "里面" },
  { fr: "extérieur", pinyin: "wàimiàn", hanzi: "外面" },
  { fr: "classificateur général", pinyin: "gè", hanzi: "个" },
  { fr: "faire", pinyin: "zuò", hanzi: "做" },
  { fr: "être", pinyin: "shì", hanzi: "是" },
  { fr: "avoir", pinyin: "yǒu", hanzi: "有" },
  { fr: "aller", pinyin: "qù", hanzi: "去" },
  { fr: "venir", pinyin: "lái", hanzi: "来" },
  { fr: "retourner", pinyin: "huí", hanzi: "回" },
  { fr: "penser / avoir envie de", pinyin: "xiǎng", hanzi: "想" },
  { fr: "vouloir", pinyin: "yào", hanzi: "要" },
  { fr: "manger", pinyin: "chī", hanzi: "吃" },
  { fr: "boire", pinyin: "hē", hanzi: "喝" },
  { fr: "parler", pinyin: "shuō", hanzi: "说" },
  { fr: "regarder", pinyin: "kàn", hanzi: "看" },
  { fr: "écouter", pinyin: "tīng", hanzi: "听" },
  { fr: "rencontrer", pinyin: "jiàn", hanzi: "见" },
  { fr: "appeler", pinyin: "jiào", hanzi: "叫" },
  { fr: "donner", pinyin: "gěi", hanzi: "给" },
  { fr: "frapper / jouer", pinyin: "dǎ", hanzi: "打" },
  { fr: "acheter", pinyin: "mǎi", hanzi: "买" },
  { fr: "vendre", pinyin: "mài", hanzi: "卖" },
  { fr: "arriver", pinyin: "dào", hanzi: "到" },
  { fr: "attendre", pinyin: "děng", hanzi: "等" },
  { fr: "apprendre", pinyin: "xué", hanzi: "学" },
  { fr: "aimer", pinyin: "xǐhuan", hanzi: "喜欢" },
  { fr: "ajouter", pinyin: "jiā", hanzi: "加" },
  { fr: "trouver", pinyin: "zhǎo", hanzi: "找" },
  { fr: "bien", pinyin: "hǎo", hanzi: "好" },
  { fr: "mauvais", pinyin: "huài", hanzi: "坏" },
  { fr: "grand", pinyin: "dà", hanzi: "大" },
  { fr: "petit", pinyin: "xiǎo", hanzi: "小" },
  { fr: "beaucoup", pinyin: "duō", hanzi: "多" },
  { fr: "peu", pinyin: "shǎo", hanzi: "少" },
  { fr: "loin", pinyin: "yuǎn", hanzi: "远" },
  { fr: "près", pinyin: "jìn", hanzi: "近" },
  { fr: "chaud", pinyin: "rè", hanzi: "热" },
  { fr: "froid", pinyin: "lěng", hanzi: "冷" },
  { fr: "garçon", pinyin: "nán", hanzi: "男" },
  { fr: "fille", pinyin: "nǚ", hanzi: "女" },
  { fr: "beau", pinyin: "piàoliang", hanzi: "漂亮" },
  { fr: "content", pinyin: "gāoxìng", hanzi: "高兴" },
  { fr: "intéressant", pinyin: "yǒuyìsi", hanzi: "有意思" },
  { fr: "très", pinyin: "hěn", hanzi: "很" },
  { fr: "trop", pinyin: "tài", hanzi: "太" },
  { fr: "à la fois", pinyin: "yòu", hanzi: "又" },
  { fr: "mais", pinyin: "dànshì", hanzi: "但是" },
  { fr: "ne... pas", pinyin: "bù", hanzi: "不" },
  { fr: "et", pinyin: "hé", hanzi: "和" },
  { fr: "mais", pinyin: "dàn", hanzi: "但" },
  { fr: "parce que", pinyin: "yīnwèi", hanzi: "因为" },
  { fr: "donc", pinyin: "suǒyǐ", hanzi: "所以" },
  { fr: "ou (affirmation)", pinyin: "huòzhě", hanzi: "或者" },
  { fr: "ou (question)", pinyin: "háishi", hanzi: "还是" },
  { fr: "si", pinyin: "rúguǒ", hanzi: "如果" },
  { fr: "par exemple", pinyin: "bǐrú", hanzi: "比如" },
  { fr: "alors", pinyin: "rán'ér", hanzi: "然而" },
  { fr: "euh...", pinyin: "nèige", hanzi: "那个" },
  { fr: "téléphone", pinyin: "diànhuà", hanzi: "电话" },
  { fr: "heure", pinyin: "xiǎoshí", hanzi: "小时" },
  { fr: "pain", pinyin: "miànbāo", hanzi: "面包" },
  { fr: "chat", pinyin: "māo", hanzi: "猫" },
  { fr: "unité monétaire (formel)", pinyin: "yuán", hanzi: "元" },
  { fr: "unité monétaire (familier)", pinyin: "kuài", hanzi: "块" },
  { fr: "alors / cependant", pinyin: "rán'ér", hanzi: "然而" },
  { fr: "quoi / que", pinyin: "shénme", hanzi: "什么" },
  { fr: "qui", pinyin: "shéi", hanzi: "谁" },
  { fr: "quand", pinyin: "shénme shíhou", hanzi: "什么时候" },
  { fr: "comment", pinyin: "zěnme", hanzi: "怎么" },
  { fr: "pourquoi", pinyin: "wèishénme", hanzi: "为什么" },
  { fr: "merci", pinyin: "xièxie", hanzi: "谢谢" },
  { fr: "de rien / pas de souci", pinyin: "bú kèqi", hanzi: "不客气" },
  { fr: "pardon / excusez-moi", pinyin: "duìbuqǐ", hanzi: "对不起" },
  { fr: "pas grave", pinyin: "méi guānxi", hanzi: "没关系" },
  { fr: "d'accord / OK", pinyin: "hǎo de", hanzi: "好的" },
  { fr: "bonjour", pinyin: "nǐ hǎo", hanzi: "你好" },
  { fr: "au revoir", pinyin: "zàijiàn", hanzi: "再见" },
  { fr: "pouvoir (capacité)", pinyin: "néng", hanzi: "能" },
  { fr: "pouvoir (autorisation)", pinyin: "kěyǐ", hanzi: "可以" },
  { fr: "devoir / should", pinyin: "yīnggāi", hanzi: "应该" },
  { fr: "comprendre", pinyin: "dǒng", hanzi: "懂" },
  { fr: "connaître / rencontrer", pinyin: "rènshi", hanzi: "认识" },
  { fr: "aimer (sentimental)", pinyin: "ài", hanzi: "爱" },
  { fr: "jeter", pinyin: "rēngdiào", hanzi: "扔掉" },
  { fr: "1", pinyin: "yī", hanzi: "一" },
  { fr: "2", pinyin: "èr", hanzi: "二" },
  { fr: "3", pinyin: "sān", hanzi: "三" },
  { fr: "4", pinyin: "sì", hanzi: "四" },
  { fr: "5", pinyin: "wǔ", hanzi: "五" },
  { fr: "6", pinyin: "liù", hanzi: "六" },
  { fr: "7", pinyin: "qī", hanzi: "七" },
  { fr: "8", pinyin: "bā", hanzi: "八" },
  { fr: "9", pinyin: "jiǔ", hanzi: "九" },
  { fr: "10", pinyin: "shí", hanzi: "十" },
  { fr: "matin", pinyin: "zǎoshàng", hanzi: "早上" },
  { fr: "midi", pinyin: "zhōngwǔ", hanzi: "中午" },
  { fr: "soir", pinyin: "wǎnshàng", hanzi: "晚上" },
  { fr: "petit-déjeuner", pinyin: "zǎofàn", hanzi: "早饭" },
  { fr: "déjeuner", pinyin: "wǔfàn", hanzi: "午饭" },
  { fr: "dîner", pinyin: "wǎnfàn", hanzi: "晚饭" },
  { fr: "médecin", pinyin: "yīshēng", hanzi: "医生" },
  { fr: "avocat (profession)", pinyin: "lǜshī", hanzi: "律师" },
  { fr: "étudiant", pinyin: "xuéshēng", hanzi: "学生" },
  { fr: "professeur", pinyin: "lǎoshī", hanzi: "老师" },
  { fr: "serveur", pinyin: "fúwùyuán", hanzi: "服务员" },
  { fr: "tofu", pinyin: "dòufu", hanzi: "豆腐" },
  { fr: "riz (cuit)", pinyin: "fàn", hanzi: "饭" },
  { fr: "soupe", pinyin: "tāng", hanzi: "汤" },
  { fr: "sucre", pinyin: "táng", hanzi: "糖" },
  { fr: "porridge", pinyin: "zhōu", hanzi: "粥" },
  { fr: "Amérique", pinyin: "měiguó", hanzi: "美国" },
  { fr: "américain", pinyin: "měiguó rén", hanzi: "美国人" },
  { fr: "Japon", pinyin: "rìběn", hanzi: "日本" },
  { fr: "japonais", pinyin: "rìběn rén", hanzi: "日本人" },
  { fr: "France", pinyin: "fǎguó", hanzi: "法国" },
  { fr: "français", pinyin: "fǎguó rén", hanzi: "法国人" },
  { fr: "français (langue)", pinyin: "fǎyǔ", hanzi: "法语" },
  { fr: "Corée", pinyin: "hánguó", hanzi: "韩国" },
  { fr: "coréen", pinyin: "hánguó rén", hanzi: "韩国人" },
  { fr: "Royaume-Uni", pinyin: "yīngguó", hanzi: "英国" },
  { fr: "anglais", pinyin: "yīngguó rén", hanzi: "英国人" },
  { fr: "aussi", pinyin: "yě", hanzi: "也" },
  { fr: "nourriture (plat)", pinyin: "cài", hanzi: "菜" },
  { fr: "librairie / bookstore", pinyin: "shūdiàn", hanzi: "书店" },
  { fr: "tasse / cup", pinyin: "bēi", hanzi: "杯子" },
  { fr: "mathématiques", pinyin: "shùxué", hanzi: "数学" },
  { fr: "musique", pinyin: "yīnyuè", hanzi: "音乐" },
  { fr: "époux", pinyin: "lǎogōng", hanzi: "老公" },
  { fr: "épouse", pinyin: "lǎopó", hanzi: "老婆" },
  { fr: "fils", pinyin: "érzi", hanzi: "儿子" },
  { fr: "fille", pinyin: "nǚ'ér", hanzi: "女儿" },
  { fr: "ma ? (particule interrogative)", pinyin: "ma", hanzi: "吗" },
  { fr: "avion", pinyin: "fēijī", hanzi: "飞机" },
  { fr: "aéroport", pinyin: "jīchǎng", hanzi: "机场" },
  { fr: "train", pinyin: "huǒchē", hanzi: "火车" },
  { fr: "gare", pinyin: "huǒchē zhàn", hanzi: "火车站" },
  { fr: "valise / bagage", pinyin: "xínglǐ", hanzi: "行李" },
  { fr: "salon", pinyin: "kètīng", hanzi: "客厅" },
  { fr: "chambre", pinyin: "wòshì", hanzi: "卧室" },
  { fr: "salle de bain", pinyin: "xǐshǒujiān", hanzi: "洗手间" },
  { fr: "portefeuille", pinyin: "qiánbāo", hanzi: "钱包" },
  { fr: "être (localisation)", pinyin: "zài", hanzi: "在" },
  { fr: "camarade de classe", pinyin: "tóngxué", hanzi: "同学" },
  { fr: "basket-ball", pinyin: "lánqiú", hanzi: "篮球" },
  { fr: "football", pinyin: "zúqiú", hanzi: "足球" },
  { fr: "tennis", pinyin: "wǎngqiú", hanzi: "网球" },
  { fr: "volley-ball", pinyin: "páiqiú", hanzi: "排球" },
  { fr: "nage / natation", pinyin: "yóuyǒng", hanzi: "游泳" },
  { fr: "courir", pinyin: "pǎobù", hanzi: "跑步" },
  { fr: "souvent", pinyin: "chángcháng", hanzi: "常常" },
  { fr: "relativement", pinyin: "bǐjiào", hanzi: "比较" },
  { fr: "pas souvent", pinyin: "bù cháng", hanzi: "不常" },
  { fr: "tous / tout / les deux", pinyin: "dōu", hanzi: "都" },
  { fr: "épicé", pinyin: "là", hanzi: "辣" },
  { fr: "cher", pinyin: "guì", hanzi: "贵" },
  { fr: "au moment de", pinyin: "de shíhou", hanzi: "的 时候" },
  { fr: "bon à manger", pinyin: "hǎochī", hanzi: "好吃" },
  { fr: "bon à boire", pinyin: "hǎohē", hanzi: "好喝" },
  { fr: "joli à regarder / beautiful", pinyin: "hǎokàn", hanzi: "好看" },
  { fr: "agréable à écouter", pinyin: "hǎotīng", hanzi: "好听" },
  { fr: "très", pinyin: "fēicháng", hanzi: "非常" },
  { fr: "célèbre", pinyin: "yǒumíng", hanzi: "有名" },
  { fr: "amusant", pinyin: "hǎowánr", hanzi: "好玩儿" },
  { fr: "s’amuser / jouer", pinyin: "wán", hanzi: "玩" },
  { fr: "printemps", pinyin: "chūntiān", hanzi: "春天" },
  { fr: "été", pinyin: "xiàtiān", hanzi: "夏天" },
  { fr: "automne", pinyin: "qiūtiān", hanzi: "秋天" },
  { fr: "hiver", pinyin: "dōngtiān", hanzi: "冬天" },
  { fr: "désordre", pinyin: "luàn", hanzi: "乱" },
  { fr: "maison", pinyin: "fángzi", hanzi: "房子" },
  { fr: "voisin", pinyin: "línjū", hanzi: "邻居" },
  { fr: "bibliothèque", pinyin: "shūjià", hanzi: "书架" },
  { fr: "ne... pas (impératif)", pinyin: "bié", hanzi: "别" },
  { fr: "réfrigérateur", pinyin: "bīngxiāng", hanzi: "冰箱" },
  { fr: "veux encore / aussi", pinyin: "háiyào", hanzi: "还要" },
  { fr: "chapeau", pinyin: "màozi", hanzi: "帽子" },
  { fr: "lampe", pinyin: "táidēng", hanzi: "台灯" },
  { fr: "vêtements", pinyin: "yīfu", hanzi: "衣服" },
  { fr: "nettoyer / Faire le ménage", pinyin: "dǎsǎo", hanzi: "打扫" },
  { fr: "d'abord / en premier", pinyin: "xiān", hanzi: "先" },
  { fr: "essuyer / nettoyer", pinyin: "cā", hanzi: "擦" },
  { fr: "choses / objets", pinyin: "dōngxi", hanzi: "东西" },
  { fr: "serpillère / balai", pinyin: "tuōbǎ", hanzi: "拖把" },
  { fr: "sale", pinyin: "zāng", hanzi: "脏" },
  { fr: "lourd", pinyin: "zhòng", hanzi: "重" },
  { fr: "lundi", pinyin: "xīngqī yī", hanzi: "星期一" },
  { fr: "mardi", pinyin: "xīngqī èr", hanzi: "星期二" },
  { fr: "mercredi", pinyin: "xīngqī sān", hanzi: "星期三" },
  { fr: "jeudi", pinyin: "xīngqī sì", hanzi: "星期四" },
  { fr: "vendredi", pinyin: "xīngqī wǔ", hanzi: "星期五" },
  { fr: "samedi", pinyin: "xīngqī liù", hanzi: "星期六" },
  { fr: "dimanche", pinyin: "xīngqī rì (ou tiān)", hanzi: "星期日 / 星期天" },
  { fr: "journal / quotidien", pinyin: "bàozhǐ", hanzi: "报纸" },
  { fr: "avoir besoin de / Il faut / need", pinyin: "xūyào", hanzi: "需要" },
  { fr: "occupé / Débordé", pinyin: "máng", hanzi: "忙" },
  { fr: "mignon / Adorable", pinyin: "kě'ài", hanzi: "可爱" },
  { fr: "aider / Aide", pinyin: "bāngzhù", hanzi: "帮助" },
  { fr: "aider (verbe seul)", pinyin: "bāng", hanzi: "帮" },
  { fr: "dormir / Sommeil", pinyin: "shuìjiào", hanzi: "睡觉" },
  { fr: "propre / nettoyer", pinyin: "gānjìng", hanzi: "干净" },
  { fr: "table", pinyin: "zhuōzi", hanzi: "桌子" },
  { fr: "chaise", pinyin: "yǐzi", hanzi: "椅子" },
  { fr: "couteau", pinyin: "dāo", hanzi: "刀" },
  { fr: "fourchette", pinyin: "chā", hanzi: "叉" },
  { fr: "cuillère", pinyin: "sháozi", hanzi: "勺子" },
  { fr: "assiette", pinyin: "pánzi", hanzi: "盘子" },
  { fr: "peu", pinyin: "diǎn", hanzi: "一点" },
  { fr: "légumes", pinyin: "shūcài", hanzi: "蔬菜" },
  { fr: "centre commercial", pinyin: "shāngchǎng", hanzi: "商场" },
  { fr: "classificateur animaux", pinyin: "zhī", hanzi: "只" },
  { fr: "action est en cours", pinyin: "zài + verbe", hanzi: "在" },
  { fr: "maintenant", pinyin: "xiànzài", hanzi: "现在" },
  { fr: "jouer (tirer, frotter)", pinyin: "lā", hanzi: "拉" },
  { fr: "vieux / Ancien (objet)", pinyin: "jiù", hanzi: "旧" },
  { fr: "utiliser", pinyin: "yòng", hanzi: "用" },
  { fr: "avec", pinyin: "gēn", hanzi: "跟" },
  { fr: "prochain", pinyin: "xià", hanzi: "下" },
  { fr: "uniquement", pinyin: "zhǐ", hanzi: "只" },
  { fr: "cadeau", pinyin: "lǐwù", hanzi: "礼物" },
  { fr: "inviter", pinyin: "yāoqǐng", hanzi: "邀请" },
  { fr: "préparer", pinyin: "zhǔnbèi", hanzi: "准备" },
  { fr: "fête", pinyin: "pàiduì", hanzi: "派对" },
  { fr: "boisson", pinyin: "yǐnliào", hanzi: "饮料" },
  { fr: "snack / grignotage", pinyin: "língshí", hanzi: "零食" },
  { fr: "type / sorte", pinyin: "zhǒng", hanzi: "种" },
  { fr: "apporter / emmener", pinyin: "dài", hanzi: "带" },
  { fr: "ensemble", pinyin: "yìqǐ", hanzi: "一起" },
  { fr: "ne pas se sentir bien", pinyin: "bù shūfu", hanzi: "不舒服" },
  { fr: "surprise", pinyin: "jīngxǐ", hanzi: "惊喜" },
  { fr: "dire / informer", pinyin: "gàosu", hanzi: "告诉" },
  { fr: "ballon", pinyin: "qìqiú", hanzi: "气球" },
  { fr: "ouvrir / tenir / organiser", pinyin: "kāi", hanzi: "开" },
  { fr: "amour (romantique)", pinyin: "àiqíng", hanzi: "爱情" },
  { fr: "intéressant / Amusant", pinyin: "yǒuqù", hanzi: "有趣" },
  { fr: "visiter (un lieu)", pinyin: "cānguān", hanzi: "参观" },
  { fr: "librairie", pinyin: "túshūguǎn", hanzi: "图书馆" },
  { fr: "poisson", pinyin: "yú", hanzi: "鱼" },
  { fr: "médicament", pinyin: "yào", hanzi: "药" },
  { fr: "à côté de / près de", pinyin: "pángbiān", hanzi: "旁边" },
  { fr: "excusez-moi", pinyin: "qǐngwèn", hanzi: "请问" },
  { fr: "grand (taille, hauteur)", pinyin: "gāo", hanzi: "高" },
  { fr: "vraiment / Réel", pinyin: "zhēn", hanzi: "真" },
  { fr: "accueillir", pinyin: "jiēdài", hanzi: "接待" },
  { fr: "présenter", pinyin: "jièshào", hanzi: "介绍" },
  { fr: "collègue", pinyin: "tóngshì", hanzi: "同事" },
  { fr: "responsabilité", pinyin: "zérèn", hanzi: "责任" },
  { fr: "horaires", pinyin: "shíjiān ānpái", hanzi: "时间安排" },
  { fr: "règles", pinyin: "guīdìng", hanzi: "规定" },
  { fr: "client", pinyin: "kèhù", hanzi: "客户" },
  { fr: "inscription", pinyin: "bàomíng", hanzi: "报名" },
  { fr: "cours", pinyin: "kèchéng", hanzi: "课程" },
  { fr: "disponible", pinyin: "yǒu kòng", hanzi: "有空" },
  { fr: "information", pinyin: "xìnxī", hanzi: "信息" },
  { fr: "expliquer", pinyin: "shuōmíng", hanzi: "说明" },
  { fr: "investisseur", pinyin: "tóuzīzhě", hanzi: "投资者" },
  { fr: "produit", pinyin: "chǎnpǐn", hanzi: "产品" },
  { fr: "procédure", pinyin: "liúchéng", hanzi: "流程" },
  { fr: "annuler", pinyin: "qǔxiāo", hanzi: "取消" },
  { fr: "contrat", pinyin: "hétóng", hanzi: "合同" },
  { fr: "envoyer", pinyin: "fāsòng", hanzi: "发送" },
  { fr: "email", pinyin: "diànzǐ yóujiàn", hanzi: "电子邮件" },
  { fr: "confirmer", pinyin: "quèrèn", hanzi: "确认" },
  { fr: "vidéo", pinyin: "shìpín", hanzi: "视频" },
  { fr: "document", pinyin: "wénjiàn", hanzi: "文件" },
  { fr: "tourisme", pinyin: "lǚyóu", hanzi: "旅游" },
  { fr: "activité", pinyin: "huódòng", hanzi: "活动" },
  { fr: "blanc", pinyin: "bái", hanzi: "白" },
  { fr: "noir", pinyin: "hēi", hanzi: "黑" },
  { fr: "rouge", pinyin: "hóng", hanzi: "红" },
  { fr: "bleu", pinyin: "lán", hanzi: "蓝" },
  { fr: "vert", pinyin: "lǜ", hanzi: "绿" },
  { fr: "jaune", pinyin: "huáng", hanzi: "黄" },
  { fr: "orange", pinyin: "chéng", hanzi: "橙" },
  { fr: "violet", pinyin: "zǐ", hanzi: "紫" },
  { fr: "rose", pinyin: "fěn", hanzi: "粉" },
  { fr: "marron", pinyin: "zōng", hanzi: "棕" },
  { fr: "gris", pinyin: "huī", hanzi: "灰" },
  { fr: "cuisiner / faire à manger", pinyin: "zuò fàn", hanzi: "做饭" },
  { fr: "télévision", pinyin: "diànshì", hanzi: "电视" },
  { fr: "emprunter / prêter", pinyin: "jiè", hanzi: "借" },
  { fr: "chocolat", pinyin: "qiǎokèlì", hanzi: "巧克力" },
  { fr: "en bonne santé / sain", pinyin: "jiànkāng", hanzi: "健康" },
  { fr: "glacé / glace", pinyin: "bīng", hanzi: "冰" },
  { fr: "gâteau", pinyin: "dàngāo", hanzi: "蛋糕" },
  { fr: "lit", pinyin: "chuáng", hanzi: "床" },
  { fr: "comment (état)", pinyin: "zěnmeyàng", hanzi: "怎么样" },
  { fr: "combien (prix)", pinyin: "duōshǎo qián", hanzi: "多少钱" },
  { fr: "combien (quantité)", pinyin: "jǐ", hanzi: "几" },
  { fr: "lequel / quel", pinyin: "nǎ", hanzi: "哪" },
  { fr: "de qui", pinyin: "shéi de", hanzi: "谁的" },
  { fr: "à quelle heure", pinyin: "jǐ diǎn", hanzi: "几点" },
  { fr: "fatigué", pinyin: "lèi", hanzi: "累" },
  { fr: "confortable / à l’aise", pinyin: "shūfu", hanzi: "舒服" },
  { fr: "cuisine", pinyin: "chúfáng", hanzi: "厨房" },
  { fr: "ordinateur", pinyin: "diànnǎo", hanzi: "电脑" },
    { fr: "ouvrir", pinyin: "dǎkāi", hanzi: "打开" },
  { fr: "fermer", pinyin: "guānbì", hanzi: "关闭" },
  { fr: "entrer", pinyin: "jìnlái", hanzi: "进来" },
  { fr: "sortir", pinyin: "chūqù", hanzi: "出去" },
  { fr: "commencer", pinyin: "kāishǐ", hanzi: "开始" },
  { fr: "finir", pinyin: "jiéshù", hanzi: "结束" },
  { fr: "marcher", pinyin: "zǒu", hanzi: "走" },
  { fr: "monter", pinyin: "shàng", hanzi: "上" },
  { fr: "descendre", pinyin: "xià", hanzi: "下" },
  { fr: "changer", pinyin: "huàn", hanzi: "换" },
  { fr: "essayer", pinyin: "shì", hanzi: "试" },
  { fr: "décider", pinyin: "juédìng", hanzi: "决定" },
  { fr: "choisir", pinyin: "xuǎnzé", hanzi: "选择" },
  { fr: "comprendre (réaliser)", pinyin: "míngbái", hanzi: "明白" },
  { fr: "se souvenir", pinyin: "jìde", hanzi: "记得" },
  { fr: "oublier", pinyin: "wàng", hanzi: "忘" },
  { fr: "croire", pinyin: "xiāngxìn", hanzi: "相信" },
  { fr: "penser (opinion)", pinyin: "juéde", hanzi: "觉得" },
  { fr: "c’est bon", pinyin: "kěyǐ le", hanzi: "可以了" },
  { fr: "pas encore", pinyin: "hái méi", hanzi: "还没" },
  { fr: "déjà", pinyin: "yǐjīng", hanzi: "已经" },
  { fr: "encore", pinyin: "hái", hanzi: "还" },
  { fr: "un peu", pinyin: "yǒudiǎn", hanzi: "有点" },
  { fr: "très bon", pinyin: "tài hǎo le", hanzi: "太好了" },
  { fr: "aucun problème", pinyin: "méi wèntí", hanzi: "没问题" },
  { fr: "attends", pinyin: "děng yíxià", hanzi: "等一下" },
  { fr: "lentement", pinyin: "màn man", hanzi: "慢慢" },
  { fr: "vite", pinyin: "kuài", hanzi: "快" },
  { fr: "toujours", pinyin: "zǒngshì", hanzi: "总是" },
  { fr: "parfois", pinyin: "yǒushíhou", hanzi: "有时候" },
  { fr: "jamais", pinyin: "cónglái bù", hanzi: "从来不" },
  { fr: "peut-être", pinyin: "kěnéng", hanzi: "可能" },
  { fr: "probablement", pinyin: "yīnggāi", hanzi: "应该" },
  { fr: "presque", pinyin: "chàbuduō", hanzi: "差不多" },
  { fr: "carte bancaire", pinyin: "yínháng kǎ", hanzi: "银行卡" },
  { fr: "paiement mobile", pinyin: "zhīfù", hanzi: "支付" },
  { fr: "police", pinyin: "jǐngchá", hanzi: "警察" },
  { fr: "hôpital", pinyin: "yīyuàn", hanzi: "医院" },
  { fr: "particule possessive / descriptive", pinyin: "de", hanzi: "的" },
  { fr: "action terminée / changement de situation", pinyin: "le", hanzi: "了" },
  { fr: "suggestion / supposition douce", pinyin: "ba", hanzi: "吧" },
  { fr: "devant", pinyin: "qiánmiàn", hanzi: "前面" },
  { fr: "derrière", pinyin: "hòumiàn", hanzi: "后面" },
  { fr: "à gauche", pinyin: "zuǒbiān", hanzi: "左边" },
  { fr: "à droite", pinyin: "yòubiān", hanzi: "右边" },
  { fr: "entre", pinyin: "zhōngjiān", hanzi: "中间" },
  { fr: "en face de", pinyin: "duìmiàn", hanzi: "对面" },
  { fr: "au-dessus de", pinyin: "shàngmiàn", hanzi: "上面" },
  { fr: "en dessous de", pinyin: "xiàmiàn", hanzi: "下面" },
  { fr: "à l’intérieur", pinyin: "lǐmiàn", hanzi: "里面" },
  { fr: "autour de", pinyin: "zhōuwéi", hanzi: "周围" },
  { fr: "pluie", pinyin: "yǔ", hanzi: "雨" },
  { fr: "pluvieux", pinyin: "yǔtiān", hanzi: "雨天" },
  { fr: "soleil", pinyin: "tàiyáng", hanzi: "太阳" },
  { fr: "ensoleillé", pinyin: "qíngtiān", hanzi: "晴天" },
  { fr: "nuage", pinyin: "yún", hanzi: "云" },
  { fr: "nuageux", pinyin: "yīntiān", hanzi: "阴天" },
  { fr: "neige", pinyin: "xuě", hanzi: "雪" },
  { fr: "neigeux", pinyin: "xiàxuě", hanzi: "下雪" },
  { fr: "équipe", pinyin: "tuánduì", hanzi: "团队" },
  { fr: "manager", pinyin: "jīnglǐ", hanzi: "经理" },
  { fr: "projet", pinyin: "xiàngmù", hanzi: "项目" },
  { fr: "objectif", pinyin: "mùbiāo", hanzi: "目标" },
  { fr: "résultat", pinyin: "jiéguǒ", hanzi: "结果" },
  { fr: "problème", pinyin: "wèntí", hanzi: "问题" },
  { fr: "solution", pinyin: "jiějué bànfǎ", hanzi: "解决办法" },
];

Object.freeze(window.VOCAB);
